name: Auto Add Reviewers Workflow

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Add Reviewers Workflow
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: RcrossF,michellejwatson,owenjaques
        re-request-when-changes-requested: true
