name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Linux build
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install build-essential libpulse-dev libasound2-dev libx11-dev libxext-dev libxinerama-dev libusb-1.0-0-dev libudev-dev
    - name: update submodules
      run: git submodule init && git submodule update
    - name: make
      working-directory: ./colorchord2
      run: make

  build-windows:
    name: Windows build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      shell: cmd
      run: git submodule init && git submodule update
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Run build script
      shell: cmd
      working-directory: .\colorchord2\windows\
      run: .\compile-clang.bat
